package com.hugorunning.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.content.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout box;SharedPreferences p;ArrayList<Race> races=new ArrayList<>();int blue=Color.rgb(15,75,170),green=Color.rgb(20,155,90),orange=Color.rgb(255,126,35),light=Color.rgb(245,248,253),ink=Color.rgb(24,38,62);
 static class Race{String n,l,d,dist;Race(String a,String b,String c,String e){n=a;l=b;d=c;dist=e;}}
 TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(ink);v.setPadding(20,12,20,12);return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 Button bt(String s,int c){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(c,32));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(4,8,4,8);b.setLayoutParams(lp);return b;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("hugo",0);seed();home();}
 void seed(){races.add(new Race("Carrera Solidaria de la Ilusión","Collado Villalba","27 SEP","Infantil"));races.add(new Race("Milla Urbana Fernando Calle","San Lorenzo de El Escorial","03 OCT","Milla infantil"));races.add(new Race("Carrera Popular El Cañaveral","Vicálvaro · Córdoba","04 OCT","Infantil"));races.add(new Race("Ruta 091 Córdoba","Casa de Campo · Córdoba","18 OCT","200 / 400 / 800 m"));races.add(new Race("Carrera por la Biodiversidad","Rivas-Vaciamadrid","18 OCT","Infantil"));races.add(new Race("Carrera Popular de Moratalaz","Moratalaz · Córdoba","08 NOV","Infantil"));}
 void base(){getWindow().setStatusBarColor(blue);ScrollView s=new ScrollView(this);s.setBackgroundColor(light);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(22,18,22,50);s.addView(box);setContentView(s);}
 void head(String sub){TextView h=tx("🏃  HUGO RUNNING",29);h.setTextColor(blue);h.setTypeface(null,1);box.addView(h);TextView x=tx(sub,15);x.setTextColor(Color.DKGRAY);box.addView(x);}
 void home(){base();head("Carreras infantiles · Comunidad de Córdoba");TextView hero=tx("MADRID CORRE CON HUGO\n\nEncuentra su próxima carrera, guarda la ficha y no olvides el dorsal.",22);hero.setTextColor(Color.WHITE);hero.setTypeface(null,1);hero.setBackground(bg(blue,38));hero.setPadding(28,32,28,32);box.addView(hero);Button search=bt("🔎  BUSCAR CARRERAS EN MADRID",orange);search.setOnClickListener(v->list(false));box.addView(search);Button mine=bt("⭐  MIS CARRERAS",blue);mine.setOnClickListener(v->list(true));box.addView(mine);TextView info=tx("✓ Solo Córdoba\n✓ Carreras infantiles\n✓ Dorsal, recorrido e inscripción\n✓ Estado de Hugo guardado",16);info.setBackground(bg(Color.WHITE,28));box.addView(info);}
 void list(boolean only){base();head(only?"Mis carreras de Hugo":"Próximas carreras en Córdoba");int count=0;for(int i=0;i<races.size();i++){if(only&&!p.getBoolean("r"+i,false))continue;count++;final int k=i;Race r=races.get(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,16,18,16);c.setBackground(bg(Color.WHITE,28));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(3,8,3,8);c.setLayoutParams(lp);TextView date=tx(r.d,14);date.setTextColor(orange);date.setTypeface(null,1);c.addView(date);TextView n=tx(r.n,19);n.setTextColor(blue);n.setTypeface(null,1);c.addView(n);c.addView(tx("📍 "+r.l+"   ·   🏃 "+r.dist,14));if(p.getBoolean("r"+i,false)){TextView ok=tx("✓ HUGO APUNTADO",14);ok.setTextColor(green);ok.setTypeface(null,1);c.addView(ok);}Button b=bt("Ver ficha completa  ›",blue);b.setOnClickListener(v->detail(k));c.addView(b);box.addView(c);}if(count==0)box.addView(tx("Todavía no has añadido carreras. Vuelve a Córdoba y elige una.",17));Button back=bt("⌂  Inicio",Color.DKGRAY);back.setOnClickListener(v->home());box.addView(back);}
 void detail(int i){base();Race r=races.get(i);head(r.n);TextView badge=tx(r.d+"   ·   📍 "+r.l,17);badge.setTextColor(Color.WHITE);badge.setBackground(bg(blue,28));box.addView(badge);String[] a={"👦 CATEGORÍA\n"+r.dist,"📅 FECHA\n"+r.d,"🎽 DORSAL\nINFORMACIÓN DE DORSAL PENDIENTE","📌 SALIDA / RECORRIDO\nPendiente de verificación oficial","💶 INSCRIPCIÓN Y PRECIO\nPendiente de verificación oficial","📄 REGLAMENTO\nConsulta siempre la fuente oficial antes de inscribir a Hugo"};for(String z:a){TextView v=tx(z,16);v.setBackground(bg(Color.WHITE,24));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(3,6,3,6);v.setLayoutParams(lp);box.addView(v);}Button web=bt("🌐  BUSCAR INFORMACIÓN OFICIAL",orange);web.setOnClickListener(v->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+Uri.encode(r.n+" "+r.l+" 2026 carrera infantil inscripción dorsal reglamento")))));box.addView(web);boolean y=p.getBoolean("r"+i,false);Button mark=bt(y?"✓ HUGO APUNTADO":"＋ AÑADIR A MIS CARRERAS",y?green:blue);mark.setOnClickListener(v->{p.edit().putBoolean("r"+i,!p.getBoolean("r"+i,false)).apply();detail(i);});box.addView(mark);Button back=bt("← Volver a Córdoba",Color.DKGRAY);back.setOnClickListener(v->list(false));box.addView(back);}
}
