package com.hugorunning.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.content.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout box;SharedPreferences p;ArrayList<Race> races=new ArrayList<>();
 static class Race{String n,l,q;Race(String a,String b,String c){n=a;l=b;q=c;}}
 TextView tx(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(16,10,16,10);return v;}
 Button bt(String s){Button b=new Button(this);b.setText(s);return b;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("hugo",0);seed();home();}
 void seed(){races.add(new Race("Carrera de la Mujer por la Igualdad","Córdoba","carrera mujer igualdad cordoba infantil reglamento"));races.add(new Race("XXI Ruta del Aceite","La Victoria","ruta aceite la victoria carrera infantil"));races.add(new Race("Memorial Joaquín Sánchez","La Carlota","memorial joaquin sanchez la carlota carrera"));races.add(new Race("XXI Legua Villa de Fernán Núñez","Fernán Núñez","legua fernan nunez carrera infantil"));races.add(new Race("Ruta de la Miel","Hornachuelos","ruta miel hornachuelos carrera infantil"));races.add(new Race("Carrera Nocturna de Alcolea","Alcolea","carrera nocturna alcolea infantil"));}
 void base(){ScrollView s=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(20,20,20,40);s.addView(box);setContentView(s);}
 void title(String sub){TextView h=tx("HUGO RUNNING",30);h.setTextColor(Color.rgb(13,71,161));box.addView(h);box.addView(tx(sub,16));}
 void home(){base();title("Carreras infantiles de Córdoba y alrededores");Button search=bt("BUSCAR CARRERAS");search.setTextSize(20);search.setOnClickListener(v->searchWeb());box.addView(search);Button all=bt("VER CARRERAS");all.setOnClickListener(v->list(false));box.addView(all);Button mine=bt("MIS CARRERAS DE HUGO");mine.setOnClickListener(v->list(true));box.addView(mine);box.addView(tx("El buscador abre una búsqueda actualizada de carreras infantiles. En cada ficha puedes consultar reglamento y marcar a Hugo como apuntado.",15));}
 void searchWeb(){Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+Uri.encode("carreras infantiles Córdoba provincia 2026 reglamento inscripción dorsal")));startActivity(i);}
 void list(boolean only){base();title(only?"Mis carreras":"Carreras encontradas");for(int i=0;i<races.size();i++){if(only&&!p.getBoolean("r"+i,false))continue;final int k=i;Race r=races.get(i);Button b=bt(r.n+"\n"+r.l+(p.getBoolean("r"+i,false)?"   ✓ HUGO APUNTADO":""));b.setAllCaps(false);b.setOnClickListener(v->detail(k));box.addView(b);}Button back=bt("VOLVER");back.setOnClickListener(v->home());box.addView(back);}
 void detail(int i){base();Race r=races.get(i);title(r.n);box.addView(tx("📍 "+r.l,18));box.addView(tx("👦 Hugo: 8–9 años",18));box.addView(tx("📅 Fecha: Pendiente de verificación",17));box.addView(tx("🏃 Categoría infantil y distancia: consultar reglamento oficial",17));box.addView(tx("⏰ Hora de salida: Pendiente de publicación",17));box.addView(tx("🎽 Recogida de dorsal: Pendiente de publicación",17));box.addView(tx("📌 Lugar de recogida: Pendiente de publicación",17));box.addView(tx("💶 Precio: Pendiente de verificación",17));box.addView(tx("📍 Salida/recorrido: Pendiente de verificación",17));Button info=bt("BUSCAR FICHA, REGLAMENTO Y DORSALES");info.setOnClickListener(v->{Intent x=new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+Uri.encode(r.q+" dorsal horario categoría 8 9 años")));startActivity(x);});box.addView(info);boolean y=p.getBoolean("r"+i,false);Button mark=bt(y?"✓ HUGO APUNTADO":"MARCAR HUGO APUNTADO");mark.setOnClickListener(v->{boolean z=!p.getBoolean("r"+i,false);p.edit().putBoolean("r"+i,z).apply();detail(i);});box.addView(mark);Button back=bt("VOLVER A CARRERAS");back.setOnClickListener(v->list(false));box.addView(back);}
}
